package pokemongame.scene.battle

import kotlin.math.ceil

const val SCREEN_WIDTH = 960f
const val SCREEN_HEIGHT = 640f

val BATTLE_DISPLAY_HEIGHT = ceil(SCREEN_HEIGHT * .75f)
val INPUT_BACKGROUND_HEIGHT = SCREEN_HEIGHT - BATTLE_DISPLAY_HEIGHT

const val HORIZONTAL_SPACING = 10f
const val VERTICAL_SPACING = 3f

val INPUT_HEIGHT = INPUT_BACKGROUND_HEIGHT - (VERTICAL_SPACING * 2 + 7f)

const val ORIGIN_Y = -(SCREEN_HEIGHT / 2f)
const val TOP_MOST_Y = -(SCREEN_HEIGHT) + VERTICAL_SPACING